services:
  newsnow:
    build: .
    ports:
      - '4444:4444'
    volumes:
      - ${HOST_DATA_DIR:-../../state/events}:/data/events
    environment:
      - DATA_DIR=/data/events
      - G_CLIENT_ID=
      - G_CLIENT_SECRET=
      - JWT_SECRET=
      - INIT_TABLE=true
      - ENABLE_CACHE=true
